<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <Import Project="..\netfx.props" />
  <PropertyGroup>
    <Version>2.0.0</Version>
    <AssemblyName>Oxide.References</AssemblyName>
    <Authors>Oxide Team and Contributors</Authors>
    <Copyright>(c) 2013-$([System.DateTime]::Now.Year) $(Authors)</Copyright>
    <Description>Dependency references for the Oxide modding framework</Description>
    <RepositoryUrl>https://github.com/OxideMod/Oxide.References</RepositoryUrl>
    <PackageIconUrl>icon.png</PackageIconUrl>
    <PackageProjectUrl>$(RepositoryUrl)</PackageProjectUrl>
    <TargetFrameworks>net48;netstandard2.0;netstandard2.1</TargetFrameworks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <NoWarn>NU1701;NU5128</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ILRepack" Version="2.0.18" GeneratePathProperty="true" PrivateAssets="all" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" GeneratePathProperty="true" PrivateAssets="all" />
    <PackageReference Include="WebSocketSharpFork" Version="1.0.4" GeneratePathProperty="true" PrivateAssets="all" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" GeneratePathProperty="true" PrivateAssets="all" />
    <Content Include="Dependencies\net48\*.*" PackagePath="lib\any\net48" />
    <Content Include="Dependencies\netstandard2.0\*.*" PackagePath="lib\any\netstandard2.0" />
    <Content Include="Dependencies\netstandard2.1\*.*" PackagePath="lib\any\netstandard2.1" />
    <Content Include="Dependencies\any\x64\*.*" PackagePath="lib\any\x64" />
    <Content Include="Dependencies\any\x86\*.*" PackagePath="lib\any\x86" />
    <Content Include="Dependencies\any\Mono.*" Exclude="Dependencies\any\Mono.Posix.dll" PackagePath="lib\any" />
    <Content Include="Dependencies\any\System.*" PackagePath="lib\any" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
  <Target Name="AfterBuild">
    <ItemGroup>
      <MergeAssemblies Include="$(TargetDir)\Oxide.References.dll" />
      <MergeAssemblies Condition="$(TargetFramework.StartsWith('net4'))" Include="$(PkgMono_Cecil)\lib\net40\Mono.Cecil.dll" />
      <MergeAssemblies Condition="$(TargetFramework.StartsWith('net4'))" Include="$(PkgMono_Cecil)\lib\net40\Mono.Cecil.Rocks.dll" />
      <MergeAssemblies Condition="$(TargetFramework.StartsWith('netstandard'))" Include="$(PkgMono_Cecil)\lib\netstandard2.0\Mono.Cecil.dll" />
      <MergeAssemblies Condition="$(TargetFramework.StartsWith('netstandard'))" Include="$(PkgMono_Cecil)\lib\netstandard2.0\Mono.Cecil.Rocks.dll" />
      <MergeAssemblies Condition="$(TargetFramework.StartsWith('net4')) AND $(TargetFramework) != 'net40'" Include="$(PkgNewtonsoft_Json)\lib\net45\Newtonsoft.Json.dll" />
      <MergeAssemblies Condition="$(TargetFramework.StartsWith('netstandard'))" Include="$(PkgNewtonsoft_Json)\lib\netstandard2.0\Newtonsoft.Json.dll" />
      <MergeAssemblies Include="$(PkgWebSocketSharpFork)\lib\net35\websocket-sharp.dll" />
      <MergeAssemblies Include="Dependencies\any\Mono.Posix.dll" />
      <MergeAssemblies Include="Dependencies\any\protobuf-net.dll" />
    </ItemGroup>
    <PropertyGroup>
      <OutputAssembly>$(TargetDir)\Oxide.References.dll</OutputAssembly>
      <Merger>$(PkgILRepack)\tools\ILRepack.exe</Merger>
    </PropertyGroup>
    <Message Text="MERGING: @(MergeAssemblies->'%(Filename)') into $(OutputAssembly)" Importance="High" />
    <Exec Command="$(Merger) /lib:$(TargetDir) /out:&quot;$(OutputAssembly)&quot; @(MergeAssemblies->'&quot;%(FullPath)&quot;', ' ')" />
  </Target>
</Project>
